version: '3'
services:
  courses.api:
    image: courses-api:latest
    container_name: courses-api
    restart: always
    ports:
      - 5000:3000
    volumes:
      - ./.env:/opt/app/.env

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 1.5